### PR TITLE
Change Royalty Payment Transfer Method

### PR DESCRIPTION
**Pull request by amilano**
- At `enforce-buy` for `fixed-quote-royalty-policy` changed `fungible::transfer-create` to `fungible::transfer` in order to avoid failure in case the creator of the token rotated the keys for the account defined by `fungible` at some point after the token was created, leaving the policy with a "stale" `creator-guard`.
- Now that `creator-guard` is only used inside `enforce-init` to validate the existence and equality of the guard provided at the token creation phase vs the guard retrieved by `fungible::details`, it doesn't seem necessary to persist it in the `policies` table. I didn't remove it though, I guess this opens the discussion as to whether it would be ideal/necessary to keep it or remove it entirely from the equation.
- Minor change: In `marmalade.repl` changed references to `fixed-quote-policy` from test blocks using `fixed-quote-royalty-policy`. The references changed from `fqp` to `fqrp`.

### CODE REVIEW

**Comment by ggobugi27** [comment]
Thanks for bringing the issue up.
We should also change the payment to `recipient` as well, both in fqp and fqrp, since there is a possibility that recipient rotated its guard in between offer and buy. 
I agree that `creator-guard` and `recipient-guard` both don't need to be saved in the table. Can you make the change as well?

**Comment by amilano** [comment]
HI @ggobugi27 will do, but before I do it, the reason I didn't do it was because I thought that being able to `transfer-create` was part of the design, at least for the recipients.

In the case of the `creator-guard`, there was no way to update/rotate them in the policy. But, for a `recipient` I thought that the thinking behind this was to allow the account that owns the token to set a different account as the beneficiary of a sale, and in case said account hasn't been created yet in the ledger of whatever coin contract that's used as the exchange currency, then `transfer-create` would create said account and transfer.

If a recipient account exists and the guards do not match (either because the wrong guards were passed or because a rotation happened after the sale was created) the buy would fail, but IMO that's easily fixable by cancelling the sale and create\ing a new one with the proper guard for the recipient in a new quote.

The `creator-guard` on the other hand was final though, and the only way to allow the token to be sold, for that sale and subsequent ones, was to revert the creator account to the old guard, but perhaps the reason for the original guard to have been changed prohibit the revert solution (one or multiple keys in the original guard was compromised for instance).

I hope my blabbering makes sense, also I might just be way off the mark as to how I thought about this. Let me know what you think and I'll execute the changes.

**Comment by ggobugi27** [comment]
I take my word back at removing `creator-guard` from schema, because we still read the `creator-guard` from quote, and the quote uses the same schema. We can just skip reading the guard when `buy` happens, which is the line below. 
https://github.com/kadena-io/marmalade/blob/2ca52fd77b0328b9f45fa4b693ce888b396c8529/pact/fixed-quote-royalty-policy.pact#L171

About recipients, we already enforce that the `recipient` account exists on the chain with the correct `recipient-guard`, so the `fungible::transfer-create` won't be doing the job of creating the account in the case of non-existent recipients. It's true that offers can expire after timeout (it cannot be canceled before timeout), but I don't see a reason to use `transfer-create` instead of `transfer`.

**Comment by amilano** [comment]
Kk, I'll adjust according your notes 👍

**Comment by amilano** [comment]
Hey @ggobugi27, I don't see `buyer-guard` being used inside `enforce-buy` in either policy, `fixed-quote-policy` nor `fixed-quote-royalty-policy`. Is this a WIP or isn't really necessary as part of the input parameters of `enforce-buy`?

**Comment by ggobugi27** [comment]
> Hey @ggobugi27, I don't see `buyer-guard` being used inside `enforce-buy` in either policy, `fixed-quote-policy` nor `fixed-quote-royalty-policy`. Is this a WIP or isn't really necessary as part of the input parameters of `enforce-buy`?

You're right that it's not used in our policies, but it still needs to be our input because we're using `token-policy-v1`. Other policies may use it differently.

**Review by ggobugi27 — APPROVED** [review]
Looks good to me.

**Review by sirlensalot — CHANGES_REQUESTED** [review]
Looks great! Please add tests to document that `rotate` works for both creator and buyer.

**Review by ggobugi27 — APPROVED** [review]

**Pull request merged**
